In [1]:
#import  necessary libraries
import numpy as np

In [3]:
new_array =np.array([[12,23,12,11,10],[23,45,23,17,29]])   # Created 2D array
print(new_array)
print(new_array.ndim) #Check the dimension of the array

[[12 23 12 11 10]
 [23 45 23 17 29]]
2


## Converting 2 D array to a different shape

## The outermost dimension will have 2 arrays, each with 5 elements:

In [6]:
#Reshape function gives a new shape to an array without changing its data
print(new_array.reshape(2,5))  

[[12 23 12 11 10]
 [23 45 23 17 29]]


In [9]:
print(new_array.reshape(5,2))  

[[12 23]
 [12 11]
 [10 23]
 [45 23]
 [17 29]]


In [16]:
print(new_array.reshape(5,5))  # throws error

ValueError: cannot reshape array of size 10 into shape (5,5)

In [17]:
#throws error
array_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

new_arr = array_1.reshape(3, 3)

print(new_arr)

ValueError: cannot reshape array of size 8 into shape (3,3)

## We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements

In [18]:
array_2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print(array_2.reshape(3,4))
print(array_2.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1


In [21]:
new_array_2 = (array_2.reshape(3,4)) #dimension shows 1D in earlier cell because similar with ravel function 
                                     # reshape did not change the original array so created a new variable to store the reshaped array

print(new_array_2)
print(new_array_2.ndim)         

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
